# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f <- function(x) {
    .Call('_StatComp20068_f', PACKAGE = 'StatComp20068', x)
}

rwC_Metropolis <- function(sigma, x0, N) {
    .Call('_StatComp20068_rwC_Metropolis', PACKAGE = 'StatComp20068', sigma, x0, N)
}

